<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * @Route("/article")
 */
class ArticleController extends Controller {

    /**
     * @Route("/", name="article_index", methods="GET")
     */
    public function index(ArticleRepository $articleRepository): Response {
        return $this->render('article/index.html.twig', ['articles' => $articleRepository->findAll()]);
        }

        /**
         * @Route("/new", name="article_new", methods="GET|POST")
         * @Security("has_role('ROLE_ADMIN')")
         */
        public function new(Request $request): Response
        {
        $article = new Article();
        $article->setFkUserId($this->getUser());
        $article->setArticleDate(new \DateTime('now'));

        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

        // $file contient le fichier jpeg uploadé
        $file = $article->getArticlePicture();

        $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

        // déplace le fichier le fichier jusqu'au dossier des images stockées
        $file->move(
        $this->getParameter('pictures_directory'),
        $fileName
        );

        // met à jour la propriété picture avec le nom du fichier jpeg
        // et non son contenu
        $article->setArticlePicture($fileName);

        $em = $this->getDoctrine()->getManager();
        $em->persist($article);
        $em->flush();

        return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
                    'article' => $article,
                    'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods="GET")
     */
    public function show(Article $article): Response {
        return $this->render('article/show.html.twig', ['article' => $article]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods="GET|POST")
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function edit(Request $request, Article $article): Response {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // $file contient le fichier jpeg uploadé
            $file = $article->getArticlePicture();

            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

            // déplace le fichier le fichier jusqu'au dossier des images stockées
            $file->move(
                    $this->getParameter('pictures_directory'), $fileName
            );

            // met à jour la propriété picture avec le nom du fichier jpeg
            // et non son contenu
            $article->setArticlePicture($fileName);


            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_edit', ['id' => $article->getId()]);
        }

        return $this->render('article/edit.html.twig', [
                    'article' => $article,
                    'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods="DELETE")
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function delete(Request $request, Article $article): Response {
        if ($this->isCsrfTokenValid('delete' . $article->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($article);
            $em->flush();
        }

        return $this->redirectToRoute('article_index');
    }

     /**
     * @return string
     */
    private function generateUniqueFileName() {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
    
}
